imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:
  nodes:
    my-tests:
      environment:
        php:
          version: 7.3
      tests:
        override:
          - command: "make phpunit"
            coverage:
              file: "clover.xml"
              format: "php-clover"
